INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (m&m&quot;s Mint Dark Chocolate,04000047367,https://fr.openfoodfacts.org/produit/04000047367/m-m-s-mint-dark-chocolate,,m&m's,42,5 g,210,d)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Chocolates)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Cookies Brownie,0059749952903,https://fr.openfoodfacts.org/produit/0059749952903/cookies-brownie-selection,,Selection,500 g,628,c)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Biscuits and cakes, Biscuits, Chocolate biscuits, Cookies, Chocolate cookies)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Crème pâtissière et flan pâtissier,0410979108063,https://fr.openfoodfacts.org/produit/0410979108063/creme-patissiere-et-flan-patissier,,,800g,94)
INSERT INTO category (cname VALUES (Groceries, Cooking helpers, Dessert mixes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Sao Tomé et Principe Noir 70%,071109,https://fr.openfoodfacts.org/produit/071109/sao-tome-et-principe-noir-70-coffea,,cofféa,,2368,e)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Chocolates, Dark chocolates)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Hafer Crunchy Schokolade,11044204,https://fr.openfoodfacts.org/produit/11044204/hafer-crunchy-schokolade-alnatura,,alnatura,750g,1820,d)
INSERT INTO category (cname VALUES (Pflanzliche Lebensmittel und Getränke, Pflanzliche Lebensmittel, Frühstücke, Getreide und Kartoffeln, Getreideprodukte, Frühstückscerealien)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (GRAN CEREALE Cioccolato,2000000038139,https://fr.openfoodfacts.org/produit/2000000038139/gran-cereale-cioccolato-mulino-bianco,www.amazon.it,MULINO BIANCO,BARILLA,230 g.,1920,d)
INSERT INTO category (cname VALUES (Snack, Snack dolci, Biscuits and cakes, Biscotti, Biscotti al cioccolato)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Vitamin Water,2035498599994,https://fr.openfoodfacts.org/produit/2035498599994/vitamin-water-hema,Hema,Hema,,84,d)
INSERT INTO category (cname VALUES (Beverages, Sweetened beverages)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Facacce di semola,2160030001182,https://fr.openfoodfacts.org/produit/2160030001182/facacce-di-semola,,,,674,c)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Cereali e patate, Pani)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Curado,2350295002738,https://fr.openfoodfacts.org/produit/2350295002738/curado,,,,1749,d)
INSERT INTO category (cname VALUES (Lácteos, Fermented foods, Productos fermentados de la leche, Quesos)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Grain Wise Original with 9 grains & seeds,26121437,https://fr.openfoodfacts.org/produit/26121437/grain-wise-original-with-9-grains-seeds-bakers-life,,Bakers Life,700 g,1060,a)
INSERT INTO category (cname VALUES (Breads)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Welness Flakes Aldi,27051832,https://fr.openfoodfacts.org/produit/27051832/welness-flakes-aldi-golden-bridge,Aldi,Golden Bridge,500 gram,1627,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux,Aliments d'origine végétale,Petit-déjeuners,Céréales et pommes de terre,Céréales et dérivés,Céréales pour petit-déjeuner,Flocons,Flocons de céréales,Corn-flakes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Oster Mischung, Schokolade,29051304,https://fr.openfoodfacts.org/produit/29051304/oster-mischung-schokolade,,,,2255,e)
INSERT INTO category (cname VALUES (en:snacks,en:sweet-snacks,en:chocolates)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Cracotte,3041090063152,https://fr.openfoodfacts.org/produit/3041090063152/cracotte-lu,Intermarché,Magasins U,Delhaize,Lu,250g,506,b)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux,Aliments d'origine végétale,Céréales et pommes de terre,Céréales et dérivés,Pains,Tartines craquantes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Confiture de Mirabelle,3045320092080,https://fr.openfoodfacts.org/produit/3045320092080/confiture-de-mirabelle-bonne-maman,,Bonne Maman,370 g e,1008,d)
INSERT INTO category (cname VALUES (Pflanzliche Lebensmittel und Getränke, Pflanzliche Lebensmittel, Brotaufstriche, Frühstücke, Frucht- und gemüsebasierte Lebensmittel, Fruchtbasierte Lebensmittel, Pflanzliche Brotaufstriche, Süße Brotaufstriche, Konfitüren und Marmeladen, Konfitüren, Fruchtkonfitüren, Plum jams, Mirabelle plum jams)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Sirop de Fraise,3052910056261,https://fr.openfoodfacts.org/produit/3052910056261/sirop-de-fraise-monin,,Monin,70 cl,1414)
INSERT INTO category (cname VALUES (Beverages, Syrups, Flavoured syrups, Strawberry syrups)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Haribo dragolo,3103220041338,https://fr.openfoodfacts.org/produit/3103220041338/haribo-dragolo,,Haribo,750 g,1473,d)
INSERT INTO category (cname VALUES (Lanches comida,Lanches doces,en:confectioneries,en:candies)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Madeleines Pur Beurre Fourrées à la Framboise,3182650008623,https://fr.openfoodfacts.org/produit/3182650008623/madeleines-pur-beurre-fourrees-a-la-framboise-lotus,,Lotus,Le Glazik,272 g (8 * 34 g),1845,e)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Biscuits and cakes, Cakes, Madeleines, Madeleines à la framboise)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Fourrés framboise,3229820791074,https://fr.openfoodfacts.org/produit/3229820791074/fourres-framboise-bjorg,Magasins U,Bjorg,29,16,565,e)
INSERT INTO category (cname VALUES (Biscuits fourrés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Saumon Atlantique fumé,3264310980101,https://fr.openfoodfacts.org/produit/3264310980101/saumon-atlantique-fume-armoric,,Armoric,240 g,741,d)
INSERT INTO category (cname VALUES (Seafood, Fishes, Salmons, Smoked fishes, Smoked salmons, Smoked salmons from farming, Produits décongelés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Filets de Flétan du Groenland,3292590841386,https://fr.openfoodfacts.org/produit/3292590841386/filets-de-fletan-du-groenland-thiriet,Thiriet,Thiriet,500g,669,a)
INSERT INTO category (cname VALUES (Frozen foods, Seafood, Fishes, Frozen fishes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Gingembre Rose Sushi Cock,3364699485072,https://fr.openfoodfacts.org/produit/3364699485072/gingembre-rose-sushi-cock,,Cock,360 g,33.4,c)
INSERT INTO category (cname VALUES (fr:Gingembre)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Favorite Selection,3415581571004,https://fr.openfoodfacts.org/produit/3415581571004/favorite-selection-haagen-dazs,Delhaize,Häagen-Dazs,4 * 100 ml,233,d)
INSERT INTO category (cname VALUES (Postres,Congelados,Postres helados,Helados y sorbetes,Helados,Tarrinas y bloques de helado)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Feuilleté Glacé Caramel,3528161506256,https://fr.openfoodfacts.org/produit/3528161506256/feuillete-glace-caramel-la-balade-gourmande,,La Balade Gourmande,356 g / 650 ml,1192,e)
INSERT INTO category (cname VALUES (Desserts, Frozen foods, Frozen desserts)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (6 Petites Crêpes de Froment Bio.,3531151111262,https://fr.openfoodfacts.org/produit/3531151111262/6-petites-crepes-de-froment-bio-biologik,,BIOLogik,240 g,941,b)
INSERT INTO category (cname VALUES (Crêpes and galettes, Crêpes, fr:Crêpes de froment)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Nectar Fraise,3556001010632,https://fr.openfoodfacts.org/produit/3556001010632/nectar-fraise-alain-milliat,,Alain Milliat,1 L,259,e)
INSERT INTO category (cname VALUES (Beverages, Plant-based foods and beverages, Plant-based beverages, Fruit-based beverages, Juices and nectars, Fruit juices and nectars, Fruit nectars, Nectars de fraise)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Yaourt à Boire Fraise,3560071019181,https://fr.openfoodfacts.org/produit/3560071019181/yaourt-a-boire-fraise-carrefour,Carrefour,Carrefour,750 g,1188,c)
INSERT INTO category (cname VALUES (Beverages, Dairies, Fermented foods, Fermented milk products, Dairy drinks, Fermented drinks, Yogurts, Fermented milk drinks, Drinkable yogurts, fr:Yaourts à boire goût fraise)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Calissons «La cure gourmande», boîte de 16 calissons. poids net 100gr,3760145790514,https://fr.openfoodfacts.org/produit/3760145790514/calissons-la-cure-gourmande-boite-de-16-calissons-poids-net-100gr,,Cure Gourmande,,1879,d)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Confectioneries, Calissons d'Aix)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Brassé Banane Fleur d'Oranger-Good Gout-90g,3770002327586,https://fr.openfoodfacts.org/produit/3770002327586/brasse-banane-fleur-d-oranger-good-gout-90g,,Good Goût,90 g,347)
INSERT INTO category (cname VALUES (Produits laitiers,Produits fermentés,Produits laitiers fermentés,Yaourts,Aliments pour bébé,Yaourts brassés,Desserts lactés pour bébé,Yaourts brassés aux fruits,Goûters et desserts pour bébé)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Em-eukal Salbei Zuckerfrei,4009077024601,https://fr.openfoodfacts.org/produit/4009077024601/em-eukal-salbei-zuckerfrei-dr-c,,Dr.C.,,992,b)
INSERT INTO category (cname VALUES (Bonbons)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Teekanne Frio Pfirsich Maracuja,4009300012078,https://fr.openfoodfacts.org/produit/4009300012078/teekanne-frio-pfirsich-maracuja,,Teekanne,,8,c)
INSERT INTO category (cname VALUES (Getränke,Alkoholfreie Getränke,Ungezuckerte Getränke)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Freeway Limonade, Orange,42143772,https://fr.openfoodfacts.org/produit/42143772/freeway-limonade-orange-lidl,Lidl,Lidl,,159,e)
INSERT INTO category (cname VALUES (Getränke, Pflanzliche Lebensmittel und Getränke, Pflanzliche Getränke, Kohlensäurehaltige Getränke, Fruchtgetränke, Erfrischungsgetränke, Fruchtlimonaden, Orangenlimonaden, Gezuckerte Getränke)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Crème au lait,4335896600741,https://fr.openfoodfacts.org/produit/4335896600741/creme-au-lait-exquisit-von-kaufland,Kaufland,Exquisit von Kaufland,2 x 100 g,682,c)
INSERT INTO category (cname VALUES (Milchdesserts)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Cereale Pufarine Din Grîu,4841765000234,https://fr.openfoodfacts.org/produit/4841765000234/cereale-pufarine-din-griu-dolce-lina,,Dolce-Lina,100 g,1647)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Breakfasts, Cereals and potatoes, Cereals and their products, Breakfast cereals, Puffed grains, Puffed cereals)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Weetabix Avena Suave Oatibix,5010029220629,https://fr.openfoodfacts.org/produit/5010029220629/weetabix-avena-suave-oatibix,,Weetabix,,1548,a)
INSERT INTO category (cname VALUES (Plant-based foods and beverages,Plant-based foods,Breakfasts,Cereals and potatoes,Cereals and their products,Breakfast cereals,Flakes,Cereal flakes,Oat flakes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Choc & mint fruit & nut bar,5013822000665,https://fr.openfoodfacts.org/produit/5013822000665/choc-mint-fruit-nut-bar-good-full-stop,www.Snackies.fr,Good full stop,35 g,569,d)
INSERT INTO category (cname VALUES (Barre aux dates)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Ancient grains,5053827188258,https://fr.openfoodfacts.org/produit/5053827188258/ancient-grains-kellogg-s,migros,Kellogg's,300 g,1674,a)
INSERT INTO category (cname VALUES (Cornflakes céréales)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Biskuttini tar-Rahal,5350145004292,https://fr.openfoodfacts.org/produit/5350145004292/biskuttini-tar-rahal-maypole,,Maypole,250 g,1213,b)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Biscuits and cakes, Biscuits)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Salade De Poulet Curry,5400112292600,https://fr.openfoodfacts.org/produit/5400112292600/salade-de-poulet-curry-delhaize,Delhaize,Delhaize,185 g,1276,d)
INSERT INTO category (cname VALUES (chicken salad)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Pains Pita Bio,5400112880401,https://fr.openfoodfacts.org/produit/5400112880401/pains-pita-bio-delhaize,Delhaize,Delhaize,350 g (5 * 70 g),1086,a)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Breads, Flatbreads, Special breads, Pitas)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Spaghetti ,5410028240121,https://fr.openfoodfacts.org/produit/5410028240121/spaghetti-tosca,,Tosca,1 kg,1481,a)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Pastas, Dry pasta, Wheat pasta, Durum wheat pasta, Spaghetti, Durum wheat spaghetti)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Meli,5410038102150,https://fr.openfoodfacts.org/produit/5410038102150/meli,Delhaize,Meli,350 g,1339)
INSERT INTO category (cname VALUES (Produits à tartiner,Petit-déjeuners,Produits à tartiner sucrés,Produits de la ruche,Produits d'élevages,Édulcorants,Miels)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Crema de cacao y avellanas,5410291023575,https://fr.openfoodfacts.org/produit/5410291023575/crema-de-cacao-y-avellanas-pralinutta,,Pralinutta,750 g,2276,e)
INSERT INTO category (cname VALUES (Cremas de cacao y avellanas)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Hippos - Dark Chocolates Sea Salt Caramel,5425031752752,https://fr.openfoodfacts.org/produit/5425031752752/hippos-dark-chocolates-sea-salt-caramel-baru,Monoprix,Barù,60 g,1874,e)
INSERT INTO category (cname VALUES (Snacks,Zoete snacks,Confiserie,Chocoladesnoep,Pralines)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Aquarius Red Peach Pet 50CL 4-pack,5449000131133,https://fr.openfoodfacts.org/produit/5449000131133/aquarius-red-peach-pet-50cl-4-pack-coca-cola,,Coca-Cola,aquarius,500ml,130,e)
INSERT INTO category (cname VALUES (Beverages, Carbonated drinks, Sodas, Non-Alcoholic beverages, Sweetened beverages)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Coca-Cola sin cafeína,5449000183217,https://fr.openfoodfacts.org/produit/5449000183217/coca-cola-sin-cafeina,,Coca-Cola,2,2L,188,e)
INSERT INTO category (cname VALUES (Bebidas, Bebidas carbonatadas, Sodas, Bebidas de cola, Cola sodas without caffeine, Bebidas azucaradas)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (E. Wedel Gorzka,5901588016030,https://fr.openfoodfacts.org/produit/5901588016030/e-wedel-gorzka-cadbury,,Cadbury,100 g e,2100,e)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Chocolates, Dark chocolates)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (DR. Oetker Musli Cu Ciocolata,5941132005196,https://fr.openfoodfacts.org/produit/5941132005196/dr-oetker-musli-cu-ciocolata,,Dr. Oetker,,1741,c)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Breakfasts, Cereals and potatoes, Cereals and their products, Breakfast cereals)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Tarama,5941880902136,https://fr.openfoodfacts.org/produit/5941880902136/tarama-pescado-group,,Pescado Group,,2301,d)
INSERT INTO category (cname VALUES (Tenger gyümölcsei, Taramasalata)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Crunchy Peanut Butter No Added Sugar and Salt,6009522300654,https://fr.openfoodfacts.org/produit/6009522300654/crunchy-peanut-butter-no-added-sugar-and-salt-black-cat,intermart,Black Cat,peanut butter,400 g,2730,c)
INSERT INTO category (cname VALUES (Fats)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Dal Makhani masala,6291103750136,https://fr.openfoodfacts.org/produit/6291103750136/dal-makhani-masala-mdh,Velan,Passage Brady à Paris,MDH,100 g,1092,c)
INSERT INTO category (cname VALUES (Groceries, Condiments)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Tubercules de moutarde marinées,6900956260067,https://fr.openfoodfacts.org/produit/6900956260067/tubercules-de-moutarde-marinees-lulu-food,,Lulu Food,138 g,126)
INSERT INTO category (cname VALUES (Pickles, Tubercule de moutarde marinée)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Knekkebrød Helsprøtt,7071848003921,https://fr.openfoodfacts.org/produit/7071848003921/knekkebr%C3%B8d-helspr%C3%B8tt-sigdal-bakeri,,Sigdal Bakeri,220 g,1950,c)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Breads, Crispbreads)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Gnocchi aux pommes de terre,7610827510892,https://fr.openfoodfacts.org/produit/7610827510892/gnocchi-aux-pommes-de-terre-betty-bossi,Coop,Betty Bossi,550 g,552,c)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux,Aliments d'origine végétale,Céréales et pommes de terre,Gnocchi,Gnocchi de pommes de terre,Gnocchi de pommes de terre réfrigérés,Légume réfrigéré)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Cenovis En Pâte,7612813110406,https://fr.openfoodfacts.org/produit/7612813110406/cenovis-en-pate,,Cenovis,1000 g,950,d)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Spreads, Plant-based spreads, Salted spreads, Yeast extract spreads)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Estrelitas,7613032199944,https://fr.openfoodfacts.org/produit/7613032199944/estrelitas-nestle,,Nestle,300g,1669,c)
INSERT INTO category (cname VALUES (Cereales para el desayuno)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Cottage Cheese,7613269453000,https://fr.openfoodfacts.org/produit/7613269453000/cottage-cheese-migros-bio,Migros,Migros Bio,250 g,380,b)
INSERT INTO category (cname VALUES (Milchprodukte, Fermentierte Lebensmittel, Brotaufstriche, Fermentierte Milch, Salted spreads, Käse, Streichkäse)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Chewing gum 2 fresh menthe verte sans sucre hollywood,7622210601049,https://fr.openfoodfacts.org/produit/7622210601049/chewing-gum-2-fresh-menthe-verte-sans-sucre-hollywood,,Hollywood,66 g (3 * 22 g),715,b)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Confectioneries, Chewing gum, Sugar-free chewing gum)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Original,7622300444181,https://fr.openfoodfacts.org/produit/7622300444181/original-oreo,,Oreo,,2008,e)
INSERT INTO category (cname VALUES (Biscuits cacaotés fourrés goût vanille)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Whole Wheat Organic Mezze Maniche Pasta,8000139910746,https://fr.openfoodfacts.org/produit/8000139910746/whole-wheat-organic-mezze-maniche-pasta-garofalo,emisfero,Garofalo,500 g,1464,a)
INSERT INTO category (cname VALUES (Pasta,integrale)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Nutella GR800 Gran Formato,8000500280706,https://fr.openfoodfacts.org/produit/8000500280706/nutella-gr800-gran-formato-ferrero,,Ferrero,Nutella,,2255,e)
INSERT INTO category (cname VALUES (Breakfasts, Spreads, Sweet spreads, Crema da spalmare, Crema con cacao, Crema con nocciole e cacao, Crema con nocciole)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Chips au citron vert et poivre rouge,8003130141782,https://fr.openfoodfacts.org/produit/8003130141782/chips-au-citron-vert-et-poivre-rouge-san-carlo,,San Carlo,,2063,e)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Snacks, Cereali e patate, Salty snacks, Appetizers, Chips and fries, Crisps, Potato crisps, Flavoured potato crisps)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Nettare di albicocca italiana,8009004908550,https://fr.openfoodfacts.org/produit/8009004908550/nettare-di-albicocca-italiana-alce-nero,,Alce Nero,200 ml,251,e)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Bevande, Plant-based beverages, Bevande a base di frutta, Succo e nettare, en:fruit-juices-and-nectars, Nettare di frutta, Nettare di albicocca)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Nice Morning,8010265651000,https://fr.openfoodfacts.org/produit/8010265651000/nice-morning-kellogg-s,,Kellogg's,375 g e,1513,b)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Colazioni, Cereali e patate, Cereals and their products, Breakfast cereals, Cereales-au-son)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Miele di arancio di Sicilia,8012666504671,https://fr.openfoodfacts.org/produit/8012666504671/miele-di-arancio-di-sicilia-terre-d-italia,,Terre d'Italia,500 g,1339)
INSERT INTO category (cname VALUES (Breakfasts, Spreads, Sweet spreads, Bee products, Farming products, Sweeteners, Miele, Miele di agrumi, Miele di arancio)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Crema Di Marroni,8018161000410,https://fr.openfoodfacts.org/produit/8018161000410/crema-di-marroni-achillea,,Achillea,330g,1079,c)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Spreads, Colazioni, Plant-based spreads, Sweet spreads, Confetture e marmellate, Confetture)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Confettura Mirtilli,80298441,https://fr.openfoodfacts.org/produit/80298441/confettura-mirtilli-zuegg,,Zuegg,,799,c)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Spreads, Colazioni, Fruits and vegetables based foods, Fruits based foods, Plant-based spreads, Sweet spreads, Confetture e marmellate, Confetture, Fruit jams, Confetture di frutti di bosco, Confetture di mirtilli)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Fussilli Bucati Corti N. 145,8076810500759,https://fr.openfoodfacts.org/produit/8076810500759/fussilli-bucati-corti-n-145-voiello,,Voiello,500 g e,1502,a)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Pastas, Wheat pasta, Pie dough, fr:Pâtes sablées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Vive Soy De Pascual Bebida De Almendra,8410128169916,https://fr.openfoodfacts.org/produit/8410128169916/vive-soy-de-pascual-bebida-de-almendra-vivesoy,Spar,Vivesoy,,113,b)
INSERT INTO category (cname VALUES (Sojamilch)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Snack multicereal,8410199015686,https://fr.openfoodfacts.org/produit/8410199015686/snack-multicereal,,,,2008,d)
INSERT INTO category (cname VALUES (Aperitivos)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Lait UHT Demi-Écrémé,8412779220107,https://fr.openfoodfacts.org/produit/8412779220107/lait-uht-demi-ecreme-solar-de-galicia,,Solar de Galicia,1 l,192,b)
INSERT INTO category (cname VALUES (Lácteos, Leches, Homogenized milks, Leche UHT, Leche semidesnatada)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Snatt's Palitos De Trigo Con Pipas,8413164005583,https://fr.openfoodfacts.org/produit/8413164005583/snatt-s-palitos-de-trigo-con-pipas-grefusa,,Grefusa,62 g,2113,d)
INSERT INTO category (cname VALUES (Alimentos y bebidas de origen vegetal,Alimentos de origen vegetal,Cereales y patatas,Panes,Productos artesanales,Colines,Palitos de pan artesanales)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Tónica,8414100244059,https://fr.openfoodfacts.org/produit/8414100244059/tonica-schweppes,,Schweppes,25 CL,151,e)
INSERT INTO category (cname VALUES (Bebidas, Bebidas carbonatadas, Sodas, Non-Alcoholic beverages, Bebidas azucaradas, Tonic water)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Galletas digestive,8431876213270,https://fr.openfoodfacts.org/produit/8431876213270/galletas-digestive-carrefour,Carrefour,Carrefour,800 g,2021,e)
INSERT INTO category (cname VALUES (Galletas y pasteles)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Gran tortelloni albahaca,8480000061485,https://fr.openfoodfacts.org/produit/8480000061485/gran-tortelloni-albahaca-hacendado,Mercadona,Hacendado,250 g,1172,d)
INSERT INTO category (cname VALUES (Pastas de trigo)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Untapan De Cangrejo, Fisch,8480000807595,https://fr.openfoodfacts.org/produit/8480000807595/untapan-de-cangrejo-fisch-hacendado,Mercadona,Hacendado,,1569,d)
INSERT INTO category (cname VALUES (Aperitivos)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Zacin Bio 250-Mo] Prirode,8600015002550,https://fr.openfoodfacts.org/produit/8600015002550/zacin-bio-250-mo-prirode-polimark,,Polimark,,619,d)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Groceries, Condiments, Spices, Spice Mix)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Plazma,8600043016093,https://fr.openfoodfacts.org/produit/8600043016093/plazma-bambi,,Bambi,150 g,1854,e)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Biscuits and cakes, Biscuits)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Mayonnaise vegan,8710448697589,https://fr.openfoodfacts.org/produit/8710448697589/mayonnaise-vegan-remia,,Remia,,1343,d)
INSERT INTO category (cname VALUES (Kruidenierswaren, Sauzen, Mayonaises)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (BRINKERS Hazelnut Chocolate Spread,8710573452688,https://fr.openfoodfacts.org/produit/8710573452688/brinkers-hazelnut-chocolate-spread,Noz et Action,BRINKERS,270g,553,d)
INSERT INTO category (cname VALUES (Ontbijten, Smeerbare producten, Zoete smeerpastas, Smeerpastas)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Milde Kwark,8712800171058,https://fr.openfoodfacts.org/produit/8712800171058/milde-kwark-campina,,Campina,1 kg,238,a)
INSERT INTO category (cname VALUES (Zuivelproducten, Gefermenteerde levensmiddelen, Gefermenteerde zuivelproducten, Kazen, Verse kazen, Kwark)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Premium Dutch Gouda,8718053514604,https://fr.openfoodfacts.org/produit/8718053514604/premium-dutch-gouda-amsterdam-cheese-company,,Amsterdam Cheese Company,480 g,1782,d)
INSERT INTO category (cname VALUES (Zuivelproducten, Gefermenteerde levensmiddelen, Gefermenteerde zuivelproducten, Kazen, Nederlandse kazen, Goudse Kazen)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Body &fit Pindapasta / Erdnussbutter, Erdnuss,8718774005603,https://fr.openfoodfacts.org/produit/8718774005603/body-fit-pindapasta-erdnussbutter-erdnuss-dody-fit,,Dody&fit,500 g,2674,d)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Legumes and their products, Spreads, Plant-based spreads, Nuts and their products, Oilseed purees, Nut butters, Legume butters, Peanut butters)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Bruschetta di pomodori,9176482563478,https://fr.openfoodfacts.org/produit/9176482563478/bruschetta-di-pomodori-costa-ligure,,Costa Ligure,180g,1085,c)
INSERT INTO category (cname VALUES (Cibi e bevande a base vegetale, Cibi a base vegetale, Fruits and vegetables based foods, Vegetables based foods, Tomatoes and tomato products)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Meadowlea Original Canola Butter,9310047010117,https://fr.openfoodfacts.org/produit/9310047010117/meadowlea-original-canola-butter,,Meadowlea,500 g,2326,e)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Spreads, Fats, Plant-based spreads, Salted spreads, Vegetable fats, Spreadable fats, Margarines, Light margarines)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Pure : nouilles de soba,5400112452165,https://fr.openfoodfacts.org/produit/5400112452165/pure-nouilles-de-soba-delhaize,Delhaize,Delhaize,420g,544,b)
INSERT INTO category (cname VALUES (Nouilles)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Jibal,6111246950869,https://fr.openfoodfacts.org/produit/6111246950869/jibal,,Jibal,,151,a)
INSERT INTO category (cname VALUES (Dairies, حليب, Skimmed milks)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Teisseire Zero sucre,2000000076424,https://fr.openfoodfacts.org/produit/2000000076424/teisseire-zero-sucre,Carrefour,Delhaize,Colruyt,others,Teisseire,60 cl,109)
INSERT INTO category (cname VALUES (Plantaardige levensmiddelen en dranken, Plantaardige levensmiddelen, Kruidenierswaren, Smaakmakers, Plantaardige smaakmakers, Aromatische planten, Kruiden, Munt, Autres goûts, Concentrée au citron)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Fasu pala original,6416453073739,https://fr.openfoodfacts.org/produit/6416453073739/fasu-pala-original-fazer,,Fazer,400g,2264,e)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Marshmallows 200g Beutel Sweets & Candy,9002859032387,https://fr.openfoodfacts.org/produit/9002859032387/marshmallows-200g-beutel-sweets-candy-woogie,,woogie,200 g,1397,d)
INSERT INTO category (cname VALUES (Snacks, Süßwaren)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Thon naturel,8422410272594,https://fr.openfoodfacts.org/produit/8422410272594/thon-naturel,,,,372,a)
INSERT INTO category (cname VALUES (Seafood,Fishes,Tunas,fr:Thons à l'huile,fr:Thons à l'huile d'olive)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Chewing gum,09815203,https://fr.openfoodfacts.org/produit/09815203/chewing-gum-hollywood,,Hollywood,14g,724,b)
INSERT INTO category (cname VALUES (Snacks, Sweet snacks, Confectioneries, Chewing gum, Sugar-free chewing gum)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Lemon Curd,0637793010567,https://fr.openfoodfacts.org/produit/0637793010567/lemon-curd-mrs-bridges,,Mrs Bridges,,1427,d)
INSERT INTO category (cname VALUES (Breakfasts, Spreads, Sweet spreads, Lemon curds)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Nouilles de sarrasin soba,4902110091076,https://fr.openfoodfacts.org/produit/4902110091076/nouilles-de-sarrasin-soba-nisshin,,Nisshin,200 g,1481,d)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Cereals and potatoes, Cereals and their products, Pastas, Buckwheat pasta, Soba)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Kefir nature,2099460040068,https://fr.openfoodfacts.org/produit/2099460040068/kefir-nature-bio,,bio,150g,285,c)
INSERT INTO category (cname VALUES (Beverages, Dairies, Fermented foods, Fermented milk products, Dairy drinks, Fermented drinks, Fermented milk drinks, Kefir)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (champignons de paris,7613312111024,https://fr.openfoodfacts.org/produit/7613312111024/champignons-de-paris-mclassic,,Mclassic,230 g,84,a)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Canned foods, Canned plant-based foods, Mushrooms and their products, Canned mushrooms, Canned champignon mushrooms, Canned whole champignon mushrooms)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (Tomato Ketchup,8715700421360,https://fr.openfoodfacts.org/produit/8715700421360/tomato-ketchup-heinz,,Heinz,1170ml - 1.35kg,435)
INSERT INTO category (cname VALUES (Groceries, Sauces, Tomato sauces, Ketchup)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Petit,8480000680624,https://fr.openfoodfacts.org/produit/8480000680624/petit-hacendado,,Hacendado,4x90g,423,b)
INSERT INTO category (cname VALUES (Dairies)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Pâte brisée Pur Beure,3248830000143,https://fr.openfoodfacts.org/produit/3248830000143/pate-brisee-pur-beure-marie,,Marie,,1533,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux,Aliments d'origine végétale,Céréales et pommes de terre,Céréales et dérivés,Pâtes à tarte,Pâtes brisées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Hoisin sauce,4316734091556,https://fr.openfoodfacts.org/produit/4316734091556/hoisin-sauce-lee-kum-kee,,Lee Kum Kee,165 mL,1218,e)
INSERT INTO category (cname VALUES (Hoisin sauces)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (St hubert bio sel de mer,3366321052379,https://fr.openfoodfacts.org/produit/3366321052379/st-hubert-bio-sel-de-mer,,St Hubert,490g,522,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux,Aliments d'origine végétale,Produits à tartiner,Matières grasses,Pâtes à tartiner végétales,Produits à tartiner salés,Matières grasses végétales,Matières grasses à tartiner,Margarines)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( 18 marrons glacés,8000300137965,https://fr.openfoodfacts.org/produit/8000300137965/18-marrons-glaces-motta,,Motta, 300 g,1378,c)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Snacks, Snacks sucrés, Confiseries, Fruits à coques et dérivés, Confiseries de fruits à coques, Marrons glacés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Biscuit Tablette Chocolat au Lait bio,3256221407167,https://fr.openfoodfacts.org/produit/3256221407167/biscuit-tablette-chocolat-au-lait-bio-u-bio,Super U,U Bio,U,150 g,2198,e)
INSERT INTO category (cname VALUES (Snacks, Snacks sucrés, Biscuits et gâteaux, Biscuits, Biscuits au chocolat, Biscuits au chocolat au lait)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Boletus,7610845355666,https://fr.openfoodfacts.org/produit/7610845355666/boletus,,,30g,1280,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Produits déshydratés, Aliments à base de plantes séchées, Champignons et produits dérivés, Champignons séchés, Cèpes déshydratés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Boulettes à la Marocaine et légumes,3248833088674,https://fr.openfoodfacts.org/produit/3248833088674/boulettes-a-la-marocaine-et-legumes-marie,Inter Marché  rue Hénon LYON 4ème,MARIE,900g,393,b)
INSERT INTO category (cname VALUES (Surgelés, Plats préparés, Plats préparés surgelés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Casino Madeleines longues,3222473273669,https://fr.openfoodfacts.org/produit/3222473273669/casino-madeleines-longues,Casino,Casino,440g,1946,d)
INSERT INTO category (cname VALUES (Snacks, Snacks sucrés, Desserts, Biscuits et gâteaux, Gâteaux, Madeleines)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Cerneaux de noix,3179142066902,https://fr.openfoodfacts.org/produit/3179142066902/cerneaux-de-noix-vahine,Intermarché,Vahiné,McCormick,50 g,2767,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Fruits à coques et dérivés, Fruits à coques, Fruits à coques décortiqués, Noix, Noix décortiquées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Chunky,3800020420003,https://fr.openfoodfacts.org/produit/3800020420003/chunky-kitkat,Lidl,KitKat,Nestlé,200 g (5 gaufrettes de 40 g),2208,e)
INSERT INTO category (cname VALUES (Snacks, Snacks sucrés, Confiseries, Confiseries chocolatées, Barres, Barres chocolatées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Cocktails d'Huiles Vierges Opti'ga Bio Partenaire,3291960014405,https://fr.openfoodfacts.org/produit/3291960014405/cocktails-d-huiles-vierges-opti-ga-bio-partenaire-emile-noel,,Émile Noël,500 ml,3766,c)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Matières grasses, Matières grasses végétales, Huiles, Mélanges d'huiles)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Crèmes brûlées à la vanille,3270160249954,https://fr.openfoodfacts.org/produit/3270160249954/cremes-brulees-a-la-vanille-picard,Picard,Picard,240 g,1286,d)
INSERT INTO category (cname VALUES (Produits laitiers, Desserts, Desserts lactés, Crèmes dessert, Crèmes brûlées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES ( Filet de merlu coulis de piquillos et tian d'aubergines,2000000022327,https://fr.openfoodfacts.org/produit/2000000022327/filet-de-merlu-coulis-de-piquillos-et-tian-d-aubergines-tres-bien-merci,,Très bien merci!,340g,285)
INSERT INTO category (cname VALUES (Plats préparés, Plats préparés au poisson)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES ( Ginger drink ,0888829601901,https://fr.openfoodfacts.org/produit/0888829601901/ginger-drink-gold-kili,g20,gold kili,180g,1687)
INSERT INTO category (cname VALUES (Boissons, Boissons chaudes, Boissons instantanées, Boissons avec sucre ajouté)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Huile de Maïs Aromatisée Gingembre et Citronnelle,20558116,https://fr.openfoodfacts.org/produit/20558116/huile-de-mais-aromatisee-gingembre-et-citronnelle-vitasia,Lidl,Vitasia,Lidl,250 ml e,3464,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Epicerie, Céréales et dérivés, Condiments, Matières grasses, Matières grasses végétales, Huiles, Huiles de céréales, Huiles de maïs, Assaisonnements, Huiles aromatisées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Maxi Hot Dog New York Style,3181238941963,https://fr.openfoodfacts.org/produit/3181238941963/maxi-hot-dog-new-york-style-charal,monoprix,Charal,160 g,1071,d)
INSERT INTO category (cname VALUES (Sandwichs, Hot-dogs)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Parmentier de Colin d'Alaska aux epinards,3270160695966,https://fr.openfoodfacts.org/produit/3270160695966/parmentier-de-colin-d-alaska-aux-epinards-picard,Picard,Picard,300 g,409,b)
INSERT INTO category (cname VALUES (Surgelés, Plats préparés, Plats préparés surgelés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Plateau 3 Légumes apéro,3280220207152,https://fr.openfoodfacts.org/produit/3280220207152/plateau-3-legumes-apero-florette,Franprix,Florette,385 g,291,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Snacks, Aliments à base de fruits et de légumes, Snacks salés, Apéritif, Frais, Légumes et dérivés, Aliments à base de plantes frais, Légumes frais)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Poêlée aux marrons, pommes et figues, sauce miel - 4 épices,3270160759606,https://fr.openfoodfacts.org/produit/3270160759606/poelee-aux-marrons-pommes-et-figues-sauce-miel-4-epices-picard,Picard,Picard,450 g,814,c)
INSERT INTO category (cname VALUES (Surgelés, Plats préparés, Plats préparés surgelés, Poêlées)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Pur jus de grenade bio ,3580283512348,https://fr.openfoodfacts.org/produit/3580283512348/pur-jus-de-grenade-bio-agidra,,Agidra,,238,d)
INSERT INTO category (cname VALUES (Boissons, Aliments et boissons à base de végétaux, Boissons à base de végétaux, Boissons aux fruits, Jus et nectars, Jus et nectars de fruits, Jus de fruits, Jus de grenade)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Syrtos aux herbes de Provence,3073780817011,https://fr.openfoodfacts.org/produit/3073780817011/syrtos-aux-herbes-de-provence,Leclerc,Syrtos,Fromageries Bel,300 g,2350,d)
INSERT INTO category (cname VALUES (Produits laitiers, Produits fermentés, Produits laitiers fermentés, Fromages, Fromages de vache, Fromages industriels, Fromages pasteurisés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( Tablette Les Grandes Lait 34% Noisettes,7610400066204,https://fr.openfoodfacts.org/produit/7610400066204/tablette-les-grandes-lait-34-noisettes-lindt,Auchan, Magasins U,Lindt,Lindt & Sprüngli,150 g e,2442,e)
INSERT INTO category (cname VALUES (Snacks, Snacks sucrés, Chocolats, Chocolats au lait, Chocolats aux noisettes, Chocolats au lait aux noisettes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( bio organic Brown Rice noodle,8718754500531,https://fr.openfoodfacts.org/produit/8718754500531/bio-organic-brown-rice-noodle-yakso,,Yakso,55g,1733,b)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Céréales et dérivés, Nouilles)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( crème glacée chocolat,3292590522124,https://fr.openfoodfacts.org/produit/3292590522124/creme-glacee-chocolat-thiriet,Thiriet,Thiriet,530 g,768,d)
INSERT INTO category (cname VALUES (Desserts, Surgelés, Desserts glacés, Glaces et sorbets, Glaces)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( flocons blanc bleu,3700392474195,https://fr.openfoodfacts.org/produit/3700392474195/flocons-blanc-bleu-scarpcooking,Zodio,ScarpCooking,50 g,1774,d)
INSERT INTO category (cname VALUES (Décors sucrés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( moutarde au moût de raisin ,1756,https://fr.openfoodfacts.org/produit/1756/moutarde-au-mout-de-raisin-courte-paille,courte paille,courte paille,100g,936,d)
INSERT INTO category (cname VALUES (Epicerie, Condiments, Sauces, Moutardes)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ( saucisse de Toulouse bio,3760099534936,https://fr.openfoodfacts.org/produit/3760099534936/saucisse-de-toulouse-bio-vitafrais,Natureo,Vitafrais,3,1270,e)
INSERT INTO category (cname VALUES (Viandes, Charcuteries, Saucisses, Saucisses françaises, Saucisses de Toulouse)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (#paprika,8710532454746,https://fr.openfoodfacts.org/produit/8710532454746/paprika-chio,,Chio,80 g,2113,d)
INSERT INTO category (cname VALUES (Snacks, Snacks salés, Apéritif, Biscuits apéritifs, Biscuits apéritifs soufflés, Biscuits apéritifs soufflés à base de maïs)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (&gt;miel Acacia Bio - 500 GR - Apidis l'epicerie de logueuil,3263620400019,https://fr.openfoodfacts.org/produit/3263620400019/miel-acacia-bio-500-gr-apidis-l-epicerie-de-logueuil,,Apidis,500 g,1264)
INSERT INTO category (cname VALUES (Petit-déjeuners, Produits à tartiner, Produits à tartiner sucrés, Produits de la ruche, Produits d'élevages, Édulcorants, Miels, Miels d'acacia, Miels liquides, Miels italiens)
INSERT INTO product (pname,code,url,energy VALUES (&quot;1,5L Rhum Blanc Old Nick 40 &deg;&quot;,3012993038080,https://fr.openfoodfacts.org/produit/3012993038080/1-5l-rhum-blanc-old-nick-40-deg,209)
INSERT INTO category (cname VALUES (Boissons, Boissons alcoolisées, Alcools forts, Eaux-de-vie, Rhums, Rhums blancs)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (&quot;1L Aperitif Anise Casanis 45 &deg;&quot;,3394215741160,https://fr.openfoodfacts.org/produit/3394215741160/1l-aperitif-anise-casanis-45-deg,Magasins U,Casanis,1 l,4)
INSERT INTO category (cname VALUES (Boissons, Boissons alcoolisées, Pastis)
INSERT INTO product (pname,code,url,quantity,energy VALUES (&quot;75CL Vin De Table Rouge Cambras 12 &deg;&quot;,3211209123743,https://fr.openfoodfacts.org/produit/3211209123743/75cl-vin-de-table-rouge-cambras-12-deg,75 cL,285)
INSERT INTO category (cname VALUES (Wines)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Escargots&quot; fourrés à la persillade,3171910670564,https://fr.openfoodfacts.org/produit/3171910670564/escargots-fourres-a-la-persillade-biscuits-mistral,,Biscuits Mistral,90 g,2117,e)
INSERT INTO category (cname VALUES (Snacks, Snacks salés, Apéritif)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;FI&quot;, Marrons glacés ,8010375032409,https://fr.openfoodfacts.org/produit/8010375032409/fi-marrons-glaces-ital-canditi,Camelot la Plaine,ITAL Canditi,240 g (12 unités),1375,c)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Snacks, Snacks sucrés, Confiseries, Fruits à coques et dérivés, Confiseries de fruits à coques, Marrons glacés, C onfisseries de fruits à bogues, Marrons glacés entiers)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Fanta&quot; ( Pomme Cerise ),5449000091178,https://fr.openfoodfacts.org/produit/5449000091178/fanta-pomme-cerise,Banque alimentaire,Fanta,The Coca Cola Company,1,5 L,138,e)
INSERT INTO category (cname VALUES (Boissons, Aliments et boissons à base de végétaux, Boissons à base de végétaux, Boissons gazeuses, Boissons aux fruits, Sodas, Sodas aux fruits, Boissons avec sucre ajouté)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Façon Haché Cuisiné&quot;,3770001868196,https://fr.openfoodfacts.org/produit/3770001868196/facon-hache-cuisine-la-boucherie-vegetarienne,,La Boucherie Végétarienne,175 g,485,b)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Plats préparés, Substituts de viande, Plats préparés d'origine végétale, Réfrigérés, Plats préparés réfrigérés)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (&quot;Hachis de Carottes, Lentilles, Cabillaud au Romarin&quot;,3560071015817,https://fr.openfoodfacts.org/produit/3560071015817/hachis-de-carottes-lentilles-cabillaud-au-romarin-carrefour-baby,Carrefour,Carrefour Baby,Carrefour,Recettes pensées par Ghislaine Arabian,230 g,284)
INSERT INTO category (cname VALUES (Aliments pour bébé, Plats principaux pour bébé, Dès 12 mois)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Hellenic Gold&quot; Olives de Kalamata Dénoyautées,5200303003134,https://fr.openfoodfacts.org/produit/5200303003134/hellenic-gold-olives-de-kalamata-denoyautees-th-petropoulos-son,,TH. Petropoulos & Son,180 g égoutté,1121,d)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Pickles, Produits de l'olivier, Pickles d'origine végétale, Olives, Olives dénoyautées, Olives noires, Olives noires dénoyautées, Olives noires en saumure)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;L'idée Poisson du Jour&quot; : Thon et Emincé de Poivrons,3276770242354,https://fr.openfoodfacts.org/produit/3276770242354/l-idee-poisson-du-jour-thon-et-emince-de-poivrons-guyader,Auchan,Guyader,110g,598,b)
INSERT INTO category (cname VALUES (Snacks, Plats préparés, Snacks salés, Apéritif, Entrées, Terrines, Terrines de poisson)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;La Traditionnelle&quot; 12 Crêpes Fait Main,3385050000017,https://fr.openfoodfacts.org/produit/3385050000017/la-traditionnelle-12-crepes-fait-main-creperie-le-masson,E.Leclerc,Leclerc,Crêperie Le Masson,500 g,1339,d)
INSERT INTO category (cname VALUES (Crêpes et galettes, Crêpes, Produits artisanaux, Crêpes sucrées, Crêpes de froment)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;La perruche&quot; Cassonade douce & croquante,3174660095274,https://fr.openfoodfacts.org/produit/3174660095274/la-perruche-cassonade-douce-croquante-beghin-say,Géant Casino,Béghin Say,1 Kg.,1761,e)
INSERT INTO category (cname VALUES (Édulcorants, Sucres, Sucres roux, Sucres de canne, Sucres en poudre)
INSERT INTO product (pname,code,url,energy,score VALUES (&quot;Le Haute Loire&quot; saucisson sec supérieur,2688494024344,https://fr.openfoodfacts.org/produit/2688494024344/le-haute-loire-saucisson-sec-superieur,1644,e)
INSERT INTO category (cname VALUES (Saucissons secs)
INSERT INTO product (pname,code,url,energy,score VALUES (&quot;Le Pédat&quot; Reblochon de savoie,0201158046241,https://fr.openfoodfacts.org/produit/0201158046241/le-pedat-reblochon-de-savoie,1377,d)
INSERT INTO category (cname VALUES (fr:Reblochon de Savoie)
INSERT INTO product (pname,code,url,energy,score VALUES (&quot;Nouveaute&quot; Rillettes De Sardine 130ML,3288370004539,https://fr.openfoodfacts.org/produit/3288370004539/nouveaute-rillettes-de-sardine-130ml,1289,d)
INSERT INTO category (cname VALUES (Viandes, Produits à tartiner, Plats préparés, Charcuteries, Produits à tartiner salés, Plats préparés au poisson, Rillettes, Préparations à base de chair de poisson, Rillettes de poissons, Rillettes de sardine)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Powder&quot; Cèpes,2000000055557,https://fr.openfoodfacts.org/produit/2000000055557/powder-cepes-feed,,Feed,3 kg (20 repas),1812,d)
INSERT INTO category (cname VALUES (Préparations en poudre, Préparations pour boisson)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (&quot;Pâtes&quot; à poêler, les tressines,3252970006538,https://fr.openfoodfacts.org/produit/3252970006538/pates-a-poeler-les-tressines-alpina,Leclerc,Alpina,350 g (4-6 personnes),1518,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Céréales et dérivés, Pâtes alimentaires, Pâtes à poêler)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (&quot;Risotto de Fenouil, Merlu Blanc, Tomate&quot;,3560071015800,https://fr.openfoodfacts.org/produit/3560071015800/risotto-de-fenouil-merlu-blanc-tomate-carrefour-baby,Carrefour,Carrefour Baby,Carrefour,Recettes pensées par Ghislaine Arabian,230 g,300)
INSERT INTO category (cname VALUES (Aliments pour bébé, Plats principaux pour bébé, Menus Poissons pour bébé, Dès 15 mois)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy VALUES (&quot;Tajine de Légumes, Poulet, Raisins secs & Curry&quot;,3560071015824,https://fr.openfoodfacts.org/produit/3560071015824/tajine-de-legumes-poulet-raisins-secs-curry-carrefour-baby,carrefour,Carrefour Baby,Carrefour,Recettes pensées par Ghislaine Arabian,230 g,293)
INSERT INTO category (cname VALUES (Aliments pour bébé, Plats principaux pour bébé, Dès 15 mois)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Mac & Cheese &quot;World's Best&quot;,0782045112015,https://fr.openfoodfacts.org/produit/0782045112015/mac-cheese-world-s-best-beecher-s,,Beecher's,20 oz (567 g),895,d)
INSERT INTO category (cname VALUES (Frozen foods, Meals, Frozen ready-made meals)
INSERT INTO product (pname,code,url,brand,energy,score VALUES (&quot;bio Multi Gold&quot; Mehrfruchtsaftgetränk 30% 1l Elopak Pfanner,9006900017606,https://fr.openfoodfacts.org/produit/9006900017606/bio-multi-gold-mehrfruchtsaftgetrank-30-1l-elopak-pfanner,Pfanner,180,e)
INSERT INTO category (cname VALUES (Boissons)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES (Extra Framboise,4011800104313,https://fr.openfoodfacts.org/produit/4011800104313/extra-framboise-schwartau,Петровский,Schwartau,340 g,967,c)
INSERT INTO category (cname VALUES (Еда и напитки из растительного сырья, Еда из растительного сырья, На завтрак, Fruits and vegetables based foods, Намазки, Fruits based foods, Plant-based spreads, Сладкие намазки, Fruit preserves, Jams, Fruit jams, Berry jams, Raspberry jams)
INSERT INTO product (pname,code,url,brand,energy,score VALUES ('Défiligne',3660005725970,https://fr.openfoodfacts.org/produit/3660005725970/defiligne-yves-rocher,Yves Rocher,4,b)
INSERT INTO category (cname VALUES (Boissons)
INSERT INTO product (pname,code,url,quantity,energy,score VALUES ('Tiptree' Barbecue Sauce,0043647862037,https://fr.openfoodfacts.org/produit/0043647862037/tiptree-barbecue-sauce,260 ml,866,d)
INSERT INTO category (cname VALUES (Epicerie, Sauces, Sauces barbecue)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ('crema' Al Balsamico,8032706290579,https://fr.openfoodfacts.org/produit/8032706290579/crema-al-balsamico-antica-acetaia-cavedoni,,Antica Acetaia Cavedoni,250 ml,1113,d)
INSERT INTO category (cname VALUES (Epicerie, Condiments, Crèmes au vinaigre)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((1-35) Pappardelle,8000139001352,https://fr.openfoodfacts.org/produit/8000139001352/1-35-pappardelle-garofalo,,Garofalo,Ebro Foods,500 g e,1516,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Céréales et dérivés, Pâtes alimentaires, Pâtes sèches, Pâtes de blé, Pâtes de blé dur, Pappardelles)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((35) Rigatoni,8000139000355,https://fr.openfoodfacts.org/produit/8000139000355/35-rigatoni-garofalo,,Garofalo,Ebro Foods,500 g e,1486,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Céréales et dérivés, Pâtes alimentaires, Pâtes sèches, Pâtes de blé, Pâtes de blé dur, Rigatoni)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((87) Radiatori,8000139004872,https://fr.openfoodfacts.org/produit/8000139004872/87-radiatori-garofalo,Dia,Garofalo,Ebro Foods,500 g e,1489,a)
INSERT INTO category (cname VALUES (Aliments et boissons à base de végétaux, Aliments d'origine végétale, Céréales et pommes de terre, Céréales et dérivés, Pâtes alimentaires, Pâtes sèches, Pâtes de blé, Pâtes de blé dur, Radiatori)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((Conflit de code barre) Houmous à l'Huile d'Olive Vierge Extra / Yaourt !!!,00607537,https://fr.openfoodfacts.org/produit/00607537/conflit-de-code-barre-houmous-a-l-huile-d-olive-vierge-extra-yaourt-marks-spencer,Trader Joe's, Marks & Spencer,Marks & Spencer,200 g e,1385,c)
INSERT INTO category (cname VALUES (Plant-based foods and beverages, Plant-based foods, Spreads, Salted spreads, Plant-based spreads, Hummus)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((Fusilli) Sauce Cheese Burger,3240931539706,https://fr.openfoodfacts.org/produit/3240931539706/fusilli-sauce-cheese-burger-lustucru-selection,Cora,Lustucru Sélection,300 g,696,c)
INSERT INTO category (cname VALUES (Plats préparés, Produits à la viande, Frais, Plats préparés à la viande, Plats à base de pâtes, Plats au bœuf, Pâtes instantanées, Plats préparés à réchauffer au micro-ondes, Plats préparés frais, Box)
INSERT INTO product (pname,code,url,stores,brand,quantity,energy,score VALUES ((poule en chocolat au lait + oeufs),3173286417125,https://fr.openfoodfacts.org/produit/3173286417125/poule-en-chocolat-au-lait-oeufs-jacquot,Spar,Jacquot,250 g,2293,e)
INSERT INTO category (cname VALUES (Snacks, Snacks sucrés, Confiseries, Chocolats, Moulages en chocolat, Aliments de Pâques, Œufs de Pâques)
